### ISSUE TITLE
The todo's card background color is missing

### ISSUE THREAD

**Issue by tkgroot** [front-wings/todo-app#13]
The card background isn't white, but should be.

**Comment by tkgroot** [comment]
Somehow an error creeped into the styles of `card__content` which changes the background color.
The color should match either `#fff` or `white`

**Comment by fswijmans** [comment]
Hi Tobias,

I see this had the label duplicate but then I found out that you removed the labels? So is this really duplicate or not?

**Comment by tkgroot** [comment]
Its really a duplicate. Sorry about the confusion. I needed to double check

**Comment by ruphin** [comment]
I think this is a duplicate of #3

**Comment by fswijmans** [comment]
Ok thanks!
