### ISSUE TITLE
Update the README with prettier badge

### ISSUE THREAD

**Issue by tkgroot** [front-wings/todo-app#14]
We are proud that we have good formatted code in our codebase and that we want our code to be formatted.
To show this please add the prettier badge to the `README.md`

```markdown
[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat-square)](https://github.com/prettier/prettier)
```

**Comment by razvan-rosu** [comment]
I'd like to pick up this issue

**Comment by ruphin** [comment]
Okay, thank you
